# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EMgegPnyGdhDhuUAsTtHEpSmp8a_ErnZ
"""

import pandas as pd

import numpy as np

recomendacao = pd.read_csv("/content/drive/MyDrive/PANDAS/recomendacao.csv", error_bad_lines=False, sep=";")

recomendacao.head(n=4)

recomendacao.shape #tamanho

recomendacao.info()

recomendacao.isnull().sum() #retorna quantidade de nulos

"""**Usando MatplotLib para criação de um gráfico em Plano Carteziano**"""

import matplotlib.pyplot as plt
#biblioteca matplotlib permite criar gráficos com apenas uma função

recomendacao.plot() #gráfico carteziano