# -*- coding: utf-8 -*-
"""aula_01_pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ovXesfzvD4rPfmBEpSnQEHsrHvYTfLU9
"""

#importando a biblioteca Pandas
import pandas as pd

dataframe = pd.read_csv

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/PANDAS/recomendacao.csv", error_bad_lines=False, sep=';')

#visualizando as 5 primeiras linhas
df.head()

df.head()

df.rename(columns={'recomendacao_dia_assinatura':'assinatura', 'recomendacao_dia_encaminhamento':'encaminhamento'})

df.head()

df = df.rename(columns={'codigo_ocorrencia4':'codigo', 'recomendacao_dia_assinatura':'assinatura', 'recomendacao_dia_encaminhamento':'encaminhamento', 'recomendacao_dia_feedback':'feedback', 'recomendacao_destinatario_sigla':'sigla'})

df.head(10)

df.shape()

df.shape

df.columns

df.dtypes

#object equivale a string

df.tail()

df.describe()

df['sigla'].unique()

petrobras = df.loc[df['sigla']=='PETROBRÁS']
petrobras.head()

anac = df.loc[df['sigla']=='ANAC']
anac.head()

anac.shape

df.groupby('recomendacao_status')['sigla'].nunique()

