# -*- coding: utf-8 -*-
"""Trabalhando_com_Datas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hI4N_3BQQ6klUOjeBwWUNJbUvV0AV3aM
"""

import pandas as pd

df1 = pd.read_excel('/content/Aracaju.xlsx')
df2 = pd.read_excel('/content/Fortaleza.xlsx')
df3 = pd.read_excel('/content/Natal.xlsx')
df4 = pd.read_excel('/content/Recife.xlsx')
df5 = pd.read_excel('/content/Salvador.xlsx')

df1.head()

df = pd.concat([df1,df2,df3,df4,df5])

df.head()

df.tail()

df.dtypes

df['Data'] = df['Data'].astype('object')

df.dtypes

df['Data'] = pd.to_datetime(df['Data'])

df.dtypes

df['Data'] = pd.to_datetime(df['Data'])

#agrupamento por ano
df.groupby(df['Data'].dt.year)['Vendas'].sum()
#agrpamento de Data por ano e soma das vendas

#Criando uma nova coluna com o ano
df['Ano_Venda'] = df['Data'].dt.year

df.sample(5)

#Calculando a diferença de dias
df['Diferença_dias'] = df['Data'] - df['Data'].min()

df.tail(5)

#Filtrando as vendas de 2019 do mês de março
vendas_marco_19 = df.loc[(df['Data'].dt.year == 2019) & (df['Data'].dt.month == 3)]

vendas_marco_19.head()

vendas_marco_19.sample(20)

