# -*- coding: utf-8 -*-
"""Trabalhando_com_planilhas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QvkehEfvv6vyaSX1K_f_M5ba-rln-Gjx
"""

import pandas as pd

df1 = pd.read_excel('/content/Aracaju.xlsx')
df2 = pd.read_excel('/content/Fortaleza.xlsx')
df3 = pd.read_excel('/content/Natal.xlsx')
df4 = pd.read_excel('/content/Recife.xlsx')
df5 = pd.read_excel('/content/Salvador.xlsx')

#esses caminhos vogam para arquivos locais e não do drive

#Juntando todos os arquivos
df = pd.concat([df1,df2,df3,df4,df5])

#amostra aleatoria
df.sample(10)

df.dtypes

#mudando type de LojaID de int64 para object(string)
df['LojaID'] = df['LojaID'].astype('object')

df.dtypes

df.isnull().sum()

df['Vendas'].mean()
#média de vendas

"""**Criando Colunas**"""

#criando a coluna receita
df['Receita'] = df['Vendas'].mul(df['Qtde'])
#cria Receita com Vendas * Quantidade

df.head()

df['Receita/Venda'] = df['Receita'] / df['Vendas']
#Cria Receita/Venda com a Recita / vendas

df.head()

#retornando o valor máximo
df['Receita'].max()

df.nlargest(3, 'Vendas')

df.nsmallest(3, 'Vendas')

