# -*- coding: utf-8 -*-
"""usando_matplt_skleran.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YTvJVZ7PGVsHjKoRulvlggN7dq1KCkiw
"""

import matplotlib

#gerar valores no espaço x e y
from sklearn.datasets import make_regression
x, y = make_regression(n_samples=200, n_features=1, noise=30)
import matplotlib.pyplot as plt

plt.scatter(x, y)
plt.show() #apresenta o gráfico
#ruido de 30 é uma "margem de erro"